/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.gui;

import com.bank.dominio.CuentaBancaria;
import com.bank.servicios.GestionCuentasBancarias;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */
public class ventanaIngresoRetiro extends javax.swing.JFrame {
    
    private String ibanOrigen, ibanDestino;
    private GestionCuentasBancarias gcb;
    private List<CuentaBancaria> lista;
    
    public ventanaIngresoRetiro(int idCliente, String ibanOrigen, List<CuentaBancaria> lista, boolean condIngreso, boolean condRetiro) {
        this.ibanOrigen = ibanOrigen;
        this.lista = lista;
        
        if(condIngreso){
            inicializarIngreso();
            AddBotton(lista);
        }
        else if(condRetiro){
            inicializarRetiro();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleIng = new javax.swing.JLabel();
        lblTitleIngreso = new javax.swing.JLabel();
        jTFRetira = new javax.swing.JTextField();
        btnIngresa = new javax.swing.JButton();
        lblTitleRet = new javax.swing.JLabel();
        lblTitleRetiro = new javax.swing.JLabel();
        jTFIngreso = new javax.swing.JTextField();
        btnRetira = new javax.swing.JButton();
        lblbanOrigenRet = new javax.swing.JLabel();
        lblbanDestinoRet = new javax.swing.JLabel();
        jTFIbanDestinoRet = new javax.swing.JTextField();
        jTFIbanOrigenRet = new javax.swing.JTextField();
        lblbanOrigenIn = new javax.swing.JLabel();
        lblbanDestinoIn = new javax.swing.JLabel();
        jTFIbanOrigenIng = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THE BANK");

        lblTitleIng.setText("INGRESO A CUENTA");

        lblTitleIngreso.setText("Cuanto desea ingresar:");

        btnIngresa.setText("Ingresa");
        btnIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaActionPerformed(evt);
            }
        });

        lblTitleRet.setText("RETIRO DE CUENTA");

        lblTitleRetiro.setText("Cuanto desea retirar:");

        btnRetira.setText("Retira");

        lblbanOrigenRet.setText("Iban Origen");

        lblbanDestinoRet.setText("Iban Destino");

        lblbanOrigenIn.setText("Iban Origen");

        lblbanDestinoIn.setText("Iban Destino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblTitleIng))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblTitleRetiro)
                                .addGap(49, 49, 49)
                                .addComponent(jTFRetira, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTitleIngreso)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTitleRet)
                                                    .addComponent(jTFIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9))
                                            .addComponent(jTFIbanOrigenIng, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 30, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTFIbanDestinoRet, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRetira)))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbanDestinoRet)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblbanOrigenRet)
                                .addGap(79, 79, 79)
                                .addComponent(jTFIbanOrigenRet, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblbanDestinoIn)
                            .addComponent(lblbanOrigenIn))
                        .addGap(65, 65, 65)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIngresa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitleIng)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbanOrigenIn)
                    .addComponent(jTFIbanOrigenIng, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbanDestinoIn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIngresa)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTitleRet)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbanOrigenRet)
                    .addComponent(jTFIbanOrigenRet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbanDestinoRet)
                    .addComponent(jTFIbanDestinoRet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetira))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleRetiro)
                    .addComponent(jTFRetira, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaActionPerformed
        try{           
            //this.ibanDestino = AddBotton(lista);
            String importeCad = jTFIngreso.getText();
            double importe = Double.parseDouble(importeCad);
            gcb = new GestionCuentasBancarias();
            gcb.hacerTransferencia(ibanOrigen, ibanDestino, importe);    
        }
        catch(Exception ex){
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnIngresaActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresa;
    private javax.swing.JButton btnRetira;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTFIbanDestinoRet;
    private javax.swing.JTextField jTFIbanOrigenIng;
    private javax.swing.JTextField jTFIbanOrigenRet;
    private javax.swing.JTextField jTFIngreso;
    private javax.swing.JTextField jTFRetira;
    private javax.swing.JLabel lblTitleIng;
    private javax.swing.JLabel lblTitleIngreso;
    private javax.swing.JLabel lblTitleRet;
    private javax.swing.JLabel lblTitleRetiro;
    private javax.swing.JLabel lblbanDestinoIn;
    private javax.swing.JLabel lblbanDestinoRet;
    private javax.swing.JLabel lblbanOrigenIn;
    private javax.swing.JLabel lblbanOrigenRet;
    // End of variables declaration//GEN-END:variables

    private void inicializarRetiro() {
        btnIngresa.setVisible(false);
        //jTFIbanDestinoIng.setVisible(false);
        jTFIbanOrigenIng.setVisible(false);
        jTFIngreso.setVisible(false);
        lblTitleIng.setVisible(false);
        lblTitleIngreso.setVisible(false);
        lblbanDestinoIn.setVisible(false);
        lblbanOrigenIn.setVisible(false);    
    }

    private void inicializarIngreso() {
        jTFIbanOrigenIng.setEditable(false);
        
//        btnRetira.setVisible(false);
//        lblbanOrigenRet.setVisible(false);
//        lblbanDestinoRet.setVisible(false);
//        jTFIbanDestinoRet.setVisible(false);
//        jTFIbanOrigenRet.setVisible(false);
//        jTFRetira.setVisible(false);
//        lblTitleRet.setVisible(false);
//        lblTitleRetiro.setVisible(false);
    }
    
    private void AddBotton(List<CuentaBancaria> lista){
        for(CuentaBancaria iban: lista){
            jComboBox1.addItem(iban.getIban());
        }
    }
}
